_BASE_: "./PANDA-VisibleBody.yml"

INFO:
  UID: 'DecDet_PANDA-VisibleBody-WithSmall'

MODEL:
  CUDA_DEVICE: "'2'"

DATASETS:
  TRAIN_ROOT: "data/panda_patch_visible_body_with_small/images/train2020"
  VAL_ROOT: "data/panda_patch_visible_body_with_small/images/val2020"
  NUM_CLASSES: 1
  CLASS_NAMES: ['person']

SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 120
  BASE_LR: 0.005

OUTPUT:
  ROOT_DIR: 'outputs/DecDet/PANDA/visible_body_with_small'