_BASE_: "../../Base.yml"

INFO:
  UID: 'DecDet_PANDA-Baseline'

MODEL:
  CUDA_DEVICE: "'2'"

DATASETS:
  TRAIN_ROOT: "data/panda_patch_visible_body/train"
  VAL_ROOT: "data/panda_patch_visible_body/test"
  NUM_CLASSES: 1
  CLASS_NAMES: ['person']

SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 120

OUTPUT:
  ROOT_DIR: 'outputs/DecDet/PANDA/baseline'